CREATE TABLE `verification_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`mediaUrl` text NOT NULL,
	`mediaType` enum('image','video') NOT NULL,
	`claimEvent` text,
	`claimLocation` text,
	`claimDate` timestamp,
	`metadataScore` decimal(5,2) DEFAULT '0',
	`visionScore` decimal(5,2) DEFAULT '0',
	`weatherScore` decimal(5,2) DEFAULT '0',
	`evidenceScore` decimal(5,2) DEFAULT '0',
	`totalScore` decimal(5,2) DEFAULT '0',
	`statusBand` enum('FALSE','AVERAGE','TRUSTABLE') NOT NULL,
	`metadataFindings` json,
	`visionFindings` json,
	`weatherFindings` json,
	`evidenceFindings` json,
	`summary` text,
	`shareToken` varchar(64),
	`isPublic` enum('true','false') NOT NULL DEFAULT 'false',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `verification_reports_id` PRIMARY KEY(`id`),
	CONSTRAINT `verification_reports_shareToken_unique` UNIQUE(`shareToken`)
);
